### ISSUE TITLE
Provide XML templates for Docbook

### ISSUE THREAD

**Issue by vogella** [vogellacompany/saneclipse#27]
Info send to @SimonScholz via email

**Comment by vogella** [comment]
Existing XML templates for WTP editor are defined via org.eclipse.wst.xml.ui.

**Comment by SimonScholz** [comment]
Can we close this issue?

**Comment by vogella** [comment]
Hey @SimonScholz what brings you this repo?
Sure we can close this one,  saneclipse is not used anymore by us.
