### ISSUE TITLE
Add keybindings for increasing and decreasing font size

### ISSUE THREAD

**Issue by SimonScholz** [vogellacompany/saneclipse#34]
Since the presentationmode with a presentation theme is not included, we want to contribute it via saneclipse with a different approach.
- Create a command, which sets an appropriate Preference for turning on and off this mode
- When activating the presentation mode, the custom user settings, which are manipulated by the presentation mode need to be stored, so that they can be restored once the presentation mode is turned off again

**Comment by vogella** [comment]
I would also be nice to have button for increasing and decreasing the font size.

**Comment by vogella** [comment]
@SimonScholz we have a pending patch for that in platform.text. Maybe you can add this to saneclipse already?

**Comment by JnRouvignac** [comment]
FYI, this Eclipse plugin can do this: https://github.com/tarlog/tarlog-plugins

**Comment by vogella** [comment]
AFAICS @tarlog does not define a licence for this code, there it cannot be used.

**Comment by JnRouvignac** [comment]
It was listed as Apache License 2.0 on https://code.google.com/p/tarlog-plugins/

**Comment by tarlog** [comment]
It's under Apache License 2.0. :wink:

**Comment by vogella** [comment]
@tarlog You should add the licence.txt to your Github repo, otherwise it is not AFAIK. Also a README.md would be nice, I think there is no automatic wiki conversion available for Googe code.

**Comment by tarlog** [comment]
I added short README.md just now.
I see that a lot of people found this plugin useful, and I'm happy about it, unfortunately  I have no time to work on this project.
To tell the truth, I don't use Eclipse anymore :grinning: 

Btw, if you (or anyone) wish to add license properly, create documentation or anything like this, feel free to create PRs and I'll merge them.

**Comment by vogella** [comment]
@tarlog create with the PR. Which IDE did you move to?

**Comment by tarlog** [comment]
Intellij IDEA.

**Comment by vogella** [comment]
@tarlog Nice. Which features in IntelliJ do you find especially superior to Eclipse?

**Comment by tarlog** [comment]
@vogella In my current work place everybody uses IntelliJ and it's hard to stay special.
IntelliJ has very nice refactoring/renaming features, for example when renaming class, it can update comments, variable names and class fields.
It has very nice Spring and Gradle integration.

But it has its own bugs and problems.
Nobody is perfect :copyright:

**Comment by vogella** [comment]
@tarlog very reasonable statement, thanks. I use Android Studio for my Android work and I personally see a few nice things in IntelliJ which I plan to provide also in Eclipse default. Keybindings for increasing the font size is definitely one of them.
